name: Run Test Job

on: [push]  # Tự kích hoạt khi có push code

jobs:
  run-test:
    runs-on: ubuntu-latest  # Sử dụng máy ảo Ubuntu của GitHub
    steps:
      - name: Chạy các câu lệnh kiểm tra
        run: |
          echo "=== Thu nghiem GitHub Actions ==="
          pwd
          bash --version
          echo "=== Pipeline chay thanh cong! ==="
